# Numpy

The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.


In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3]) #creating array
print(a)

[1 2 3]


In [4]:
x=([(1,2,3),(4,5,6)]) #2d array
print(x)

[(1, 2, 3), (4, 5, 6)]


In [5]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
print(c)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [9]:
np.zeros((3)) #creat array of zero

array([0., 0., 0.])

In [11]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [19]:
d = np.arange(10,25,5) 

In [20]:
d

array([10, 15, 20])

In [21]:
f = np.eye(2)      #Create a 2X2 identity matrix
print(f)


[[1. 0.]
 [0. 1.]]


In [22]:
 np.random.random((2,2))

array([[0.35536514, 0.3436526 ],
       [0.99037128, 0.06538076]])

In [23]:
np.empty((3,2))       #Create an empty array

array([[7.20881520e+159, 5.02034658e+175],
       [1.25769939e-075, 4.05427792e+174],
       [2.23189251e+180, 1.39295105e+165]])

In [24]:
a

array([1, 2, 3])

In [25]:
a.shape           #Array dimensions

(3,)

In [26]:
len(a)

3

In [28]:
a.ndim            #Number of array dimensions



1

In [29]:
a.size            #Number of array elements

3

In [31]:
a.dtype           #Data type of array elements



dtype('int64')

In [33]:
a.astype(float) #Convert an array to a different type


array([1., 2., 3.])

In [35]:

 np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [43]:
x=np.array([4,5,6])
y=np.array([7,8,9])

In [44]:
g=y - x
print (g)


[3 3 3]


In [45]:
g=x+y

In [46]:
g

array([11, 13, 15])

In [47]:
np.subtract(y,x)  #Subtraction

array([3, 3, 3])

In [49]:
np.add(y,x)    #Addition

array([11, 13, 15])

In [50]:


x/ y          #Division



array([0.57142857, 0.625     , 0.66666667])

In [51]:


x * y          #Multiplication



array([28, 40, 54])

In [52]:


np.exp(y) #Exponentiation



array([1096.63315843, 2980.95798704, 8103.08392758])

In [53]:
np.sqrt(x) #Square root

array([2.        , 2.23606798, 2.44948974])

In [56]:
print(x,y)

[4 5 6] [7 8 9]


In [57]:
x == y   #Element-wise comparison

array([False, False, False])

In [58]:
x < 2 

array([False, False, False])

In [59]:
y>x

array([ True,  True,  True])

In [60]:
np.array_equal(x, y) #Array-wise comparison

False

In [61]:
a

array([1, 2, 3])

In [62]:


a.sum() #Array-wise sum



6

In [63]:


a.min()

1

In [65]:
a.max()

3

In [66]:


a.max(axis=0) #Maximum value of an array row



3

In [67]:
a.mean() #Mean

2.0

In [68]:
np.corrcoef(a) #Correlation coefficient

1.0

In [69]:


h = a.view()   #Create a view of the array with the same data



In [70]:
np.copy(a)

array([1, 2, 3])

In [73]:


h = a.copy() #Create a deep copy of the array

In [74]:
h

array([1, 2, 3])

In [75]:


a.sort()  #Sort an array



In [79]:
x=np.array([10,2,5,9])

In [80]:
x.sort()

In [81]:
x

array([ 2,  5,  9, 10])

In [82]:
x[2]   # Select the element at the 2nd index 3

9

In [84]:
y

array([7, 8, 9])

In [86]:


a[0:2] #Select items at index 0 and 1

array([1, 2])