## Using NumPy

Once you've installed NumPy you can import it as a library:

In [16]:
import numpy as np

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [17]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [18]:
np.array(my_list)

array([1, 2, 3])

In [19]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange

Return evenly spaced values within a given interval.

In [21]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,13,2)

array([ 0,  2,  4,  6,  8, 10, 12])

## zero and ones

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones(3)

array([1., 1., 1.])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [27]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [28]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [30]:
np.random.rand(2)

array([0.29406667, 0.31948535])

In [31]:
np.random.rand(5,5)

array([[0.50825767, 0.1128404 , 0.36521967, 0.19542057, 0.71838824],
       [0.73178572, 0.41788188, 0.96250942, 0.46750994, 0.66268227],
       [0.08785397, 0.07069586, 0.20479434, 0.54576824, 0.98142851],
       [0.11877301, 0.66527932, 0.1014075 , 0.51582696, 0.50101247],
       [0.67391168, 0.38447181, 0.38517084, 0.59892911, 0.97958662]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [32]:
np.random.randn(2)

array([0.56703951, 0.93370551])

In [33]:
np.random.randn(5,5)

array([[-0.80045872, -0.60601907, -0.01571181,  0.28316597, -0.84690079],
       [ 0.95060838,  1.75009035,  1.53533685, -1.03602183,  0.13917038],
       [ 0.11741379,  2.217253  ,  0.51139288, -1.63094296, -1.84839062],
       [-0.88119778, -0.04732636, -0.31162288,  2.01066095, -1.53856631],
       [ 0.51079917, -0.28801115, -1.60679753, -1.35710827, -0.23640623]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [34]:
np.random.randint(1,100)

21

In [35]:
np.random.randint(1,100,10)

array([35, 43, 77, 42, 46, 95, 44, 37, 50, 98])