In [1]:
import numpy as np

In [3]:
print(np._version_)

1.16.5


In [5]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

Initial Placeholders¶

In [14]:
np.zeros(3,4)

TypeError: data type not understood

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [20]:
np.arange(1,25,5) # Create an array of evenly spaced values (step value) 

array([ 1,  6, 11, 16, 21])

In [21]:
np.linspace(0,2,9)    #Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
e = np.full((2,2),7)    # Create a constant array
print(e)

[[7 7]
 [7 7]]


In [23]:
f = np.eye(2)      #Create a 2X2 identity matrix
print(f)

[[1. 0.]
 [0. 1.]]


In [24]:
np.random.random((2,2))    #Create an array with random values

array([[0.20366202, 0.91190854],
       [0.93746765, 0.53298856]])

In [25]:
np.empty((3,2))       #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [26]:
np.int64   #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
np.complex #Complex numbers represented by 128 floats
np.bool    #Boolean type storing TRUE and FALSE values
np.object  #Python object type
np.string_ #Fixed-length string type
np.unicode_ #Fixed-length unicode type

numpy.str_

In [27]:
a.shape           #Array dimensions

(3,)

In [28]:
len(a)            #Length of array

3

In [29]:
b.ndim            #Number of array dimensions

2

In [30]:
e.size            #Number of array elements

4

In [31]:
b.dtype           #Data type of array elements

dtype('float64')

In [32]:
b.dtype.name      #Name of data type

'float64'

In [33]:
b.astype(int)     #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
 #np.info(np.ndarray.dtype) #asking for help

In [39]:
print(a)

[1 2 3]


In [40]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [41]:
a-b

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [42]:
np.subtract(a,b)  #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [43]:
b + a             #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [44]:
a / b          #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [45]:
np.divide(a,b) #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [46]:
a * b          #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [47]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [48]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [49]:
np.sin(a) #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [50]:
np.cos(b) #Element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [51]:
np.log(a) #Element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [52]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

In [53]:
a == b


array([[False,  True,  True],
       [False, False, False]])

In [54]:
a


array([1, 2, 3])

In [55]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [56]:
a < 2    #Element-wise compariso

array([ True, False, False])

In [57]:
np.array_equal(a, b) #Array-wise comparison

False

In [58]:
#Aggregate Functions

In [59]:
a.sum() #Array-wise su

6

In [60]:
a.min() #Array-wise minimum value

1

In [61]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [62]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [63]:
a.mean() #Mean

2.0

In [64]:
np.median(b) #Median

3.5

In [65]:
np.corrcoef(a) #Correlation coefficien

1.0

In [66]:
np.std(b) #Standard deviation

1.5920810978785667

In [67]:
#copy array

In [68]:
h = a.view()   #Create a view of the array with the same data

In [69]:
h

array([1, 2, 3])

In [70]:
np.copy(a) #Create a copy of the array

array([1, 2, 3])

In [71]:
h = a.copy() #Create a deep copy of the array

In [72]:
#Sorting Arrays

In [73]:
a.sort()  #Sort an array

In [74]:
a

array([1, 2, 3])

In [75]:
x=([9,3.4,2])

In [78]:
x.sort()
x

[2, 3.4, 9]

In [83]:
c.sort(axis=0)  #Sort the elements of an array's axis

In [85]:
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [86]:
#Subsetting

In [87]:
a[2]   # Select the element at the 2nd index 3

3

In [88]:
b[1,2] #Select the element at row 1 column 2 (equivalent to b[1][2])

6.0

In [89]:
#Slicing

In [90]:
a[0:2] #Select items at index 0 and 1

array([1, 2])

In [91]:
b[0:2,1] #Select items at rows 0 and 1 in column 1

array([2., 5.])

In [92]:
b[:1] #Select all items at row 0 (equivalent to b[0:1, :])

array([[1.5, 2. , 3. ]])

In [93]:
c[1,...] #Same as [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [94]:
a[ : :-1] #Reversed array a array([3, 2, 1])


array([3, 2, 1])

In [95]:
#Boolean Indexing

In [96]:
a[a<2] #Select elements from a less than 2

array([1])

In [97]:
#Fancy Indexing

In [98]:
b[[1, 0, 1, 0],[0, 1, 2, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)

array([4. , 2. , 6. , 1.5])

In [99]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [100]:
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [101]:
#Transposing Array

In [102]:
i = np.transpose(b)          #Permute array dimensions

In [103]:
i.T                          #Permute array dimensions

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [104]:
#Changing Array Shape

In [105]:
b.ravel()                    #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [107]:
b.reshape(3,-2)              #Reshape, but don’t change data

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [108]:
#Adding/Removing Element

In [115]:
np.insert(a, 1, 5)  
#Return a new array with shape (2,6)

array([1, 5, 2, 3])

In [116]:
np.delete(a,[1])             #Delete items from an array

array([1, 3])

In [117]:
#Combining Arrays

In [120]:
np.concatenate((a,a),axis=0) #Concatenate arrays

array([1, 2, 3, 1, 2, 3])

In [121]:
np.vstack((a,b))             #Stack arrays vertically (row-wise)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [122]:
np.r_[e,f]                   #Stack arrays vertically (row-wise

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [123]:
np.hstack((e,f))             #Stack arrays horizontally (column-wise)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [126]:
np.hsplit(a,3)               #Split the array horizontally at the 3rd index

[array([1]), array([2]), array([3])]

In [127]:
np.vsplit(c,2)               #Split the array vertically at the 2nd index

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]